from lxml import etree as ET

# Crear el elemento raíz
packageB = ET.Element("packageB")


for i in range(1, 6):
    child = ET.SubElement(packageB, "pin", param1=f"p{i}1", param2=f"p{i}2")


# Crear un árbol de elementos
tree = ET.ElementTree(packageB)

# Escribir el árbol en un archivo XML con DOCTYPE
with open("output.xml", "wb") as f:
    f.write(b'<!DOCTYPE SimulIDE">\n\n')
    f.write(b'<!-- This file was generated by veri2sim -->\n\n')
    tree.write(f, encoding="utf-8", xml_declaration=False, pretty_print=True)