
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALWAYS AND ASSIGN BEGIN BITAND BITNOT BITOR BITXOR CASE COMMA DEFAULT DIVIDE ELSE END ENDCASE ENDFUNCTION ENDMODULE ENDTASK EQ EQEQ FOR FOREVER FUNCTION GE GT IDENTIFIER IF INITIAL INPUT LBRACE LE LPAREN LSHIFT LT MINUS MODULE NEGEDGE NEQ NOT NUMBER OR OUTPUT PLUS POSEDGE RBRACE REG REPEAT RPAREN RSHIFT SEMI TASK TIMES WHILE WIREmodule : MODULE IDENTIFIER LPAREN port_list RPAREN SEMI module_items ENDMODULEport_list : port\n                 | port_list COMMA portport : INPUT IDENTIFIER\n            | OUTPUT IDENTIFIERmodule_items : module_item\n                    | module_items module_itemmodule_item : wire_declaration\n                   | assignmentwire_declaration : WIRE IDENTIFIER SEMIassignment : ASSIGN IDENTIFIER EQ IDENTIFIER SEMI'
    
_lr_action_items = {'MODULE':([0,],[2,]),'$end':([1,21,],[0,-1,]),'IDENTIFIER':([2,7,8,19,20,26,],[3,11,12,23,24,27,]),'LPAREN':([3,],[4,]),'INPUT':([4,10,],[7,7,]),'OUTPUT':([4,10,],[8,8,]),'RPAREN':([5,6,11,12,14,],[9,-2,-4,-5,-3,]),'COMMA':([5,6,11,12,14,],[10,-2,-4,-5,-3,]),'SEMI':([9,23,27,],[13,25,28,]),'WIRE':([13,15,16,17,18,22,25,28,],[19,19,-6,-8,-9,-7,-10,-11,]),'ASSIGN':([13,15,16,17,18,22,25,28,],[20,20,-6,-8,-9,-7,-10,-11,]),'ENDMODULE':([15,16,17,18,22,25,28,],[21,-6,-8,-9,-7,-10,-11,]),'EQ':([24,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'module':([0,],[1,]),'port_list':([4,],[5,]),'port':([4,10,],[6,14,]),'module_items':([13,],[15,]),'module_item':([13,15,],[16,22,]),'wire_declaration':([13,15,],[17,17,]),'assignment':([13,15,],[18,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> MODULE IDENTIFIER LPAREN port_list RPAREN SEMI module_items ENDMODULE','module',8,'p_module','parser.py',18),
  ('port_list -> port','port_list',1,'p_port_list','parser.py',26),
  ('port_list -> port_list COMMA port','port_list',3,'p_port_list','parser.py',27),
  ('port -> INPUT IDENTIFIER','port',2,'p_port','parser.py',42),
  ('port -> OUTPUT IDENTIFIER','port',2,'p_port','parser.py',43),
  ('module_items -> module_item','module_items',1,'p_module_items','parser.py',47),
  ('module_items -> module_items module_item','module_items',2,'p_module_items','parser.py',48),
  ('module_item -> wire_declaration','module_item',1,'p_module_item','parser.py',63),
  ('module_item -> assignment','module_item',1,'p_module_item','parser.py',64),
  ('wire_declaration -> WIRE IDENTIFIER SEMI','wire_declaration',3,'p_wire_declaration','parser.py',68),
  ('assignment -> ASSIGN IDENTIFIER EQ IDENTIFIER SEMI','assignment',5,'p_assignment','parser.py',72),
]
