from lxml import etree as ET


class Component():
    def __init__(self, name, inputs, outputs):        
        self.name = name
        self.inputs = inputs
        self.outputs = outputs

    def create_package(self):
        # root element
        packageB = ET.Element("packageB", 
                              name="Package", 
                              width="8", 
                              height="{}".format(max(len(self.inputs), len(self.outputs)) + 1), 
                              background="", 
                              type="None")

        for index, value in enumerate(self.inputs):     # inputs
            pin = ET.SubElement(packageB, "pin", 
                                type="",
                                xpos="-8",
                                ypos="{}".format(8+(index*8)),
                                angle="180",
                                length="8",  
                                space="0",   
                                id="{}".format(value),     
                                label="{}".format(value))

        for index, value in enumerate(self.outputs):     # outputs
            pin = ET.SubElement(packageB, "pin", 
                                type="",
                                xpos="72",
                                ypos="{}".format(8+(index*8)),
                                angle="0",
                                length="8",  
                                space="0",   
                                id="{}".format(value),     
                                label="{}".format(value))


        # elements tree
        tree = ET.ElementTree(packageB)

        # file's header and content
        with open("{}.package".format(self.name), "wb") as f:
            f.write(b'<!DOCTYPE SimulIDE>\n\n')
            f.write(b'<!-- This file was generated by veri2sim -->\n\n')
            tree.write(f, encoding="utf-8", xml_declaration=False, pretty_print=True)


    def create_mcu(self):
        # root element
        iou = ET.Element("iou", 
                         name="{}".format(self.name), 
                         core="scripted", 
                         script="{}.as".format(self.name))

        # inputs
        ioport = ET.SubElement(iou, "ioport", 
                               name="InputPort", 
                               pins=",".join(self.inputs))
        
        # outputs
        ioport = ET.SubElement(iou, "ioport", 
                               name="OutputPort", 
                               pins=",".join(self.outputs))
        
        # element tree
        tree = ET.ElementTree(iou)

        # file's header and content
        with open("{}.mcu".format(self.name), "wb") as f:
            f.write(b'<!DOCTYPE SimulIDE>\n\n')
            f.write(b'<!-- This file was generated by veri2sim -->\n\n')
            tree.write(f, encoding="utf-8", xml_declaration=False, pretty_print=True)
