// This file was generated by veri2sim

IoPin@ aPin = component.getPin("a");
IoPin@ bPin = component.getPin("b");
IoPin@ cPin = component.getPin("c");

// ___global_definitions___

void setup()
{
	print("xor_gate setup()");
}

void reset()
{
	print("xor_gate reset()");

	aPin.setPinMode(1); // Input
	aPin.changeCallBack(element, true);
	bPin.setPinMode(1); // Input
	bPin.changeCallBack(element, true);
	cPin.setPinMode(3); // Output
	cPin.setOutState(false);
}

void voltChanged()
{
	// ___implementation___
	cPin.setOutState(aPin.getInpState() ^ bPin.getInpState());
}
