// This file was generated by veri2sim

IoPort@ aPort = component.getPort("aPort");
IoPort@ bPort = component.getPort("bPort");

// ___global_definitions___
uint v = 0;

void setup()
{
	print("array_not setup()");
}

void reset()
{
	print("array_not reset()");

	aPort.setPinMode(1); // Input
	aPort.changeCallBack(element, true);
	bPort.setPinMode(3); // Output
	bPort.setOutState(0);
}

void voltChanged()
{
	// ___implementation___
	v = ~aPort.getInpState();
	bPort.setOutState(v);
}
