// This file was generated by veri2sim

IoPin@ xPin = component.getPin("x");
IoPin@ yPin = component.getPin("y");
IoPin@ zPin = component.getPin("z");
IoPin@ cPin = component.getPin("c");

// ___global_definitions___

void setup()
{
	print("half_adder setup()");
}

void reset()
{
	print("half_adder reset()");

	xPin.setPinMode(1); // Input
	xPin.changeCallBack(element, true);
	yPin.setPinMode(1); // Input
	yPin.changeCallBack(element, true);
	zPin.setPinMode(3); // Output
	zPin.setOutState(false);
	cPin.setPinMode(3); // Output
	cPin.setOutState(false);
}

void voltChanged()
{
	// ___implementation___
	cPin.setOutState(xPin.getInpState() & yPin.getInpState());
	zPin.setOutState(xPin.getInpState() ^ yPin.getInpState());
}
